# Generated by Django 5.0.2 on 2024-02-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_aboutme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/article')),
            ],
        ),
        migrations.AlterModelOptions(
            name='aboutme',
            options={'verbose_name': '(درباره من)', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(verbose_name='توضیحات بیشتر'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='تلفن'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='article.photo'),
        ),
    ]
