# Generated by Django 5.0.2 on 2024-02-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_remove_article_image_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='article.photo'),
        ),
    ]
