# Generated by Django 5.0.2 on 2024-02-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='', verbose_name=models.ImageField(blank=True, null=True, upload_to='image/photo'))),
            ],
        ),
    ]
