# Generated by Django 5.0.2 on 2024-02-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
