# Generated by Django 5.0.2 on 2024-02-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
