# Generated by Django 5.0.2 on 2024-02-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_alter_comment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='Articles', to='article.category'),
        ),
    ]
